# Generated by Django 5.2 on 2025-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=255)),
                ('invoices', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Invoice Analysis',
                'verbose_name_plural': 'Invoice Analyses',
                'ordering': ['-id'],
            },
        ),
    ]
