# Generated by Django 5.2 on 2025-06-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='icon',
        ),
        migrations.AddField(
            model_name='tool',
            name='logo',
            field=models.ImageField(default='', upload_to='tool_logos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
