# Generated by Django 5.2 on 2025-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tool_icon_tool_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
