# Generated by Django 5.2 on 2025-06-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tool_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='documentation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='support_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
